CREATE TABLE USERSTACK(
USER_ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
USER_NAME CHAR(40),
USER_PASS CHAR(40),
VOTED INT
)

CREATE TABLE TEAM(
TEAM_ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
TEAM_NAME CHAR(40)
)

CREATE TABLE PLAYERSTACK(
PLAYER_ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
TEAM_ID INT,
UNI_NUM CHAR(40),
PLAYER_NAME CHAR(40),
FOREIGN KEY (TEAM_ID) REFERENCES TEAM (TEAM_ID)
)

CREATE TABLE MVP(
GAME_ID INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
TEAM_ID INT,
PLAYER_ID INT,
FOREIGN KEY (TEAM_ID) REFERENCES TEAM (TEAM_ID),
FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERSTACK (PLAYER_ID)
)

DROP TABLE PLAYERSTACK
