/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2017-11-22 07:55:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_005fuser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"add_user.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"common.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t    <form class=\"user-info\" action=\"/MY_MVP/q3Login\" method=\"post\">\r\n");
      out.write("\t    \tユーザー名<input type=\"text\" name=\"name\">\r\n");
      out.write("\t    \tパスワード<input type=\"password\"  name=\"pass\">\r\n");
      out.write("\t    \tパスワード再確認<input type=\"password\"  name=\"re_pass\">\r\n");
      out.write("\t    \t応援する球団\r\n");
      out.write("\t      \t<ul class=\"pacific\">\r\n");
      out.write("\t        \t<li><input type=\"checkbox\" name=\"team\" value=\"ソフトバンク\">ソフトバンク</li>\r\n");
      out.write("\t        \t<li><input type=\"checkbox\" name=\"team\" value=\"西武\">西武</li>\r\n");
      out.write("\t        \t<li><input type=\"checkbox\" name=\"team\" value=\"楽天\">楽天</li>\r\n");
      out.write("\t\t        <li><input type=\"checkbox\" name=\"team\" value=\"オリックス\">オリックス</li>\r\n");
      out.write("\t\t        <li><input type=\"checkbox\" name=\"team\" value=\"日ハム\">日ハム</li>\r\n");
      out.write("\t\t        <li><input type=\"checkbox\" name=\"team\" value=\"ロッテ\">ロッテ</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"central\">\r\n");
      out.write("\t        \t<li><input type=\"checkbox\" name=\"team\" value=\"広島\">広島</li>\r\n");
      out.write("\t        \t<li><input type=\"checkbox\" name=\"team\" value=\"阪神\">阪神</li>\r\n");
      out.write("\t\t        <li><input type=\"checkbox\" name=\"team\" value=\"DeNA\">DeNA</li>\r\n");
      out.write("\t\t        <li><input type=\"checkbox\" name=\"team\" value=\"巨人\">巨人</li>\r\n");
      out.write("\t\t        <li><input type=\"checkbox\" name=\"team\" value=\"中日\">中日</li>\r\n");
      out.write("\t\t        <li><input type=\"checkbox\" name=\"team\" value=\"ヤクルト\">ヤクルト</li>\r\n");
      out.write("\t      \t</ul>\r\n");
      out.write("\t    \t<input type=\"submit\" name=\"btn\" value=\"確定\">\r\n");
      out.write("\t    </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
