CREATE TABLE ID_TBL(
	ID VARCHAR(50),
	PASS VARCHAR(50)
)

	DROP TABLE ID_TBL
	INSERT INTO Q3_TBL (ID,PASS) VALUES('kin','dai')
	SELECT * FROM  Q3_TBL

CREATE TABLE Q3_TBL(
	ID VARCHAR(50),
	PASS VARCHAR(50)
)

