CREATE TABLE MSG_TBL (
ID INT PRIMARY KEY NOT NULL,
MSG VARCHAR(50) NOT NULL
)

INSERT INTO MSG_TBL(ID,MSG) values(1,'あれ')
INSERT INTO MSG_TBL(ID,MSG) values(2,'これ')
INSERT INTO MSG_TBL(ID,MSG) values(3,'それ')

UPDATE MSG_TBL SET MSG = '元気だけが取り柄です' WHERE ID = 3

DELETE FROM MSG_TBL WHERE ID = 2

SELECT * FROM MSG_TBL
