CREATE TABLE NOTE (
ID INT PRIMARY KEY NOT NULL,
NAME VARCHAR(50) NOT NULL,
EMALE VARCHAR(50),
KAKIKOMIDAT VARCHAR(50) NOT NULL,
KAKIKOMI VARCHAR(500) NOT NULL
)

select * from NOTE

CREATE TABLE A (
ID INT PRIMARY KEY NOT NULL,
NAME VARCHAR(50) NOT NULL
)

DROP TABLE NOTE
