/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2017-07-27 09:05:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.regex.*;

public final class ex3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
 request.setCharacterEncoding("UTF-8"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

String path = application.getRealPath("quetion.txt");
String btn = request.getParameter("btn");
String name =  request.getParameter("name");
String num = request.getParameter("num");
String add = request.getParameter("add");
String s = request.getParameter("s");
String te = request.getParameter("te");
String ta = request.getParameter("ta");
String w = request.getParameter("w");
String a = request.getParameter("a");
String p = request.getParameter("p");
String f = request.getParameter("t_name3");
try {
	if("送信".equals(btn)){
		if(s == null || te == null || ta == null || w == null || a == null){
			out.print("すべての項目に回答してください<br>");
			throw new IOException();
		}


		if(name.equals("") ){
			out.println("名前を入力してください<br>");
			throw new IOException();
		}
		if(num.equals("") ){
			out.println("学籍番号を入力してください<br>");
			throw new IOException();
		}
		if(add.equals("") ){
			out.println("メールアドレスを入力してください<br>");
			throw new IOException();
		}
		Pattern pattern = Pattern.compile("\\d{10}");
		Matcher matcher =pattern.matcher(num);
		boolean b = matcher.matches();
		if(b == false){
			out.println("学籍番号が正しくありません<br>");
			throw new IOException();
		}
		pattern = Pattern.compile("\\w+@\\w+");
		matcher =pattern.matcher(add);
		b = matcher.matches();
		if(b == false){
			out.println("アドレスが正しくありません<br>");
			throw new IOException();
		}
		out.println("<br>");
		FileWriter fw = new FileWriter(path, true);
		BufferedWriter bw = new BufferedWriter(fw);
		bw.write(num);
		bw.write(",");
		bw.write(name);
		bw.write(",");
		bw.write(add);
		bw.write(",");
		bw.write(s);
		bw.write(",");
		bw.write(te);
		bw.write(",");
		bw.write(ta);
		bw.write(",");
		bw.write(w);
		bw.write(",");
		bw.write(a);
		bw.write(",");
		bw.write(p);
		bw.write(",");
		bw.write(f);
		bw.newLine();
		bw.close();
		fw.close();
	}
	try {
		if("送信".equals(btn)){
			String str1;
			FileReader fr = new FileReader(application.getRealPath("quetion.txt"));
			BufferedReader br = new BufferedReader(fr);
			while ((str1 = br.readLine()) != null) {
				String[] str2 = str1.split(",");
				out.print("学籍番号："+ str2[0] +"<br>");
				out.print("氏名："+ str2[1] +"<br>");
				out.print("メールアドレス："+ str2[2] +"<br>");
				out.print("設問1："+ str2[3] +"<br>");
				out.print("設問2："+ str2[4] +"<br>");
				out.print("設問3："+ str2[5] +"<br>");
				out.print("設問4："+ str2[6] +"<br>");
				out.print("設問5："+ str2[7] +"<br>");
				out.print("設問6："+ str2[8] +"<br>");
				out.print("設問7："+ str2[9] +"<br>");
			}
			br.close();
			fr.close();
		}
	} catch(IOException e) {
	out.print("");
	}
} catch(IOException e) {
out.print("");
}

request.setCharacterEncoding("UTF-8");

if ("初期化".equals(btn)) {
	try {
		FileWriter fw = new FileWriter(path, false);
		BufferedWriter bw = new BufferedWriter(fw);
		bw.write("");
		bw.close();
		fw.close();
	} catch(IOException e) {
	out.print("ファイル書き込みエラー" + e);
	}
	try {
		String str;
		FileReader fr = new FileReader(application.getRealPath("quetion.txt"));
		BufferedReader br = new BufferedReader(fr);
		while ((str = br.readLine()) != null) {
		out.print(str + "<br>");
		}
		br.close();
		fr.close();
	} catch(IOException e) {
	out.print("エラーです" + e);
	}
}

      out.write("\r\n");
      out.write("<a href=\"http://localhost:8080/LECTURE7/ex3.html\">アンケートページに戻る</a>\r\n");
      out.write("<form method=\"post\" action=\"ex3.jsp\">\r\n");
      out.write("<input type=\"submit\" name=\"btn\" value=\"初期化\">\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tline-height: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
